version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - AWS_REGION=ap-southeast-1
      - PORT=3000
      # AWS Credentials (for development only)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      # Add other environment variables as needed
      - SQS_PROCESSING_QUEUE_URL=${SQS_PROCESSING_QUEUE_URL}
      - SQS_REVIEW_QUEUE_URL=${SQS_REVIEW_QUEUE_URL}
      - S3_BUCKET=${S3_BUCKET}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID}
    depends_on:
      - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data

volumes:
  dynamodb-data: 